// Code generated by alef — DO NOT EDIT.
// alef:hash:441815c8880ab94357ab46e65ee7f098d78c817836d4a5cecbca8822289c9503
package xberg

// RequireNativeSetup_1_1_4 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_1_4 = "1.1.4"
