// Code generated by alef — DO NOT EDIT.
// alef:hash:e97b7c029a29da32ed903d9861996daceefaf7a7aba5a0e4d3cda2ea7395868d
package xberg

// RequireNativeSetup_1_3_4 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_3_4 = "1.3.4"
