// Code generated by alef — DO NOT EDIT.
// alef:hash:2cbe777e80da8b458ada1323a5dd0e089893e9f329c996f30f6178f146ef37aa
package xberg

// RequireNativeSetup_1_1_0 is a version-skew sentinel referenced by the
// machine-local cgo link shim that `cmd/setup` writes into consumer packages. If this
// module is upgraded without re-running `cmd/setup`, the previously written shim (built
// against the old version) references an identifier that no longer exists here, turning
// silent native-library skew into a compile-time error instead of a runtime crash.
const RequireNativeSetup_1_1_1 = "1.1.1"
