# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:925cac9b490c0bdad63a69c2e2d59e7931f370c27ae33c5f609ed5ca996d047e
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.1.5"
end
