# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:71dc9990e02ee56c24327e6bf2b5874c3d7c8a177543612ea54d00c7891b0a16
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.1.1"
end
