# This file is auto-generated by alef — DO NOT EDIT.
# alef:hash:b27bcf116f7d5dec9c7278cd662f93e13ba51460490348bade51c096c52c1798
# To regenerate: alef generate
# To verify freshness: alef verify
# frozen_string_literal: true

module Xberg
  ## The version string for this package.
  VERSION = "1.1.2"
end
